server:
  port: 8088
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.92.109.27:3306/themis?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/themis_test?characterEncoding=utf-8
    username: root
    password: ruilin
#    password: uAiqwVwjJ8-i
  profiles:
    active: properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: localhost
    port: 6379
    password:
#    password: beitahouse.3
  mail:
    host: smtp.163.com
    username:
    password:
    default-encoding: UTF-8
logging:
  config: classpath:config/logback.xml
